name: test.yml
on:
  push:
    branches:
      - dev
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Verify Test DLL Path
        run: ls /home/runner/work/PandoraLibCSharp/PandoraLibCSharp/Tests/bin/Debug/net8.0/
      - name: Run tests
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
      - name: Show test results
        run: cat test_results.trx
